[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fluf = "D9KddH1TpYtNCcZ5igZLrXbreJVHGEmMqfzbkhST9MwS"
borrower_sample = "BiBiaMTWecRB3cbz6oMfrKq3F1VKCRLCxKgS3NYLTMCK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jordan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
