[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fluf = "2qxVaPhpX8XxNGyNZrnNe4UKD8q2dVNC5NL1WzCnGxaL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jordan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
