[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fluf = "7Crsw9yaDiT5jMZ8yWJgkdVeWpLirh9G5hJZCp9G1Aiy"
borrower_sample = "5N7gCufd5hEVkcHVSwtUmAKaHvNNagkq7T4qcUYzJ91y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jordan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
